// Frontend için temel yetki tanımlamaları
export enum Permission {
  USER_VIEW = 'user:view',
  USER_CREATE = 'user:create',
  USER_UPDATE = 'user:update',
  USER_DELETE = 'user:delete',
  USER_MANAGE_ROLES = 'user:manage_roles',
  PROJECT_VIEW = 'project:view',
  PROJECT_CREATE = 'project:create',
  PROJECT_UPDATE = 'project:update',
  PROJECT_DELETE = 'project:delete',
  TASK_VIEW = 'task:view',
  TASK_CREATE = 'task:create',
  TASK_UPDATE = 'task:update',
  TASK_DELETE = 'task:delete',
  CLIENT_VIEW = 'client:view',
  CLIENT_CREATE = 'client:create',
  CLIENT_UPDATE = 'client:update',
  CLIENT_DELETE = 'client:delete',
  EQUIPMENT_VIEW = 'equipment:view',
  EQUIPMENT_CREATE = 'equipment:create',
  EQUIPMENT_UPDATE = 'equipment:update',
  EQUIPMENT_DELETE = 'equipment:delete',
  MAINTENANCE_VIEW = 'maintenance:view',
  MAINTENANCE_CREATE = 'maintenance:create',
  MAINTENANCE_UPDATE = 'maintenance:update',
  MAINTENANCE_DELETE = 'maintenance:delete',
  EXPORT_DATA = 'export:data',
  FILE_VIEW = 'file:view',
  FILE_UPLOAD = 'file:upload',
  FILE_DELETE = 'file:delete',
  EMAIL_TEMPLATE_MANAGE = 'email_template:manage',
  ANALYTICS_VIEW = 'analytics:view',
}

export enum Role {
  ADMIN = 'ADMIN',
  FIRMA_SAHIBI = 'FIRMA_SAHIBI',
  PROJE_YONETICISI = 'PROJE_YONETICISI',
  DEPO_SORUMLUSU = 'DEPO_SORUMLUSU',
  TEKNISYEN = 'TEKNISYEN',
}

export const rolePermissions: Record<Role, Permission[]> = {
  [Role.ADMIN]: [
    Permission.USER_VIEW,
    Permission.USER_CREATE,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.USER_MANAGE_ROLES,
    Permission.PROJECT_VIEW,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_UPDATE,
    Permission.TASK_DELETE,
    Permission.CLIENT_VIEW,
    Permission.CLIENT_CREATE,
    Permission.CLIENT_UPDATE,
    Permission.CLIENT_DELETE,
    Permission.EQUIPMENT_VIEW,
    Permission.EQUIPMENT_CREATE,
    Permission.EQUIPMENT_UPDATE,
    Permission.EQUIPMENT_DELETE,
    Permission.MAINTENANCE_VIEW,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_DELETE,
    Permission.EXPORT_DATA,
    Permission.FILE_VIEW,
    Permission.FILE_UPLOAD,
    Permission.FILE_DELETE,
    Permission.EMAIL_TEMPLATE_MANAGE,
    Permission.ANALYTICS_VIEW,
  ],
  [Role.FIRMA_SAHIBI]: [
    Permission.USER_VIEW,
    Permission.USER_CREATE,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.USER_MANAGE_ROLES,
    Permission.PROJECT_VIEW,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_UPDATE,
    Permission.TASK_DELETE,
    Permission.CLIENT_VIEW,
    Permission.CLIENT_CREATE,
    Permission.CLIENT_UPDATE,
    Permission.CLIENT_DELETE,
    Permission.EQUIPMENT_VIEW,
    Permission.EQUIPMENT_CREATE,
    Permission.EQUIPMENT_UPDATE,
    Permission.EQUIPMENT_DELETE,
    Permission.MAINTENANCE_VIEW,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_DELETE,
    Permission.EXPORT_DATA,
    Permission.FILE_VIEW,
    Permission.FILE_UPLOAD,
    Permission.FILE_DELETE,
    Permission.EMAIL_TEMPLATE_MANAGE,
    Permission.ANALYTICS_VIEW,
  ],
  [Role.PROJE_YONETICISI]: [
    Permission.PROJECT_VIEW,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_UPDATE,
    Permission.TASK_DELETE,
    Permission.CLIENT_VIEW,
    Permission.CLIENT_CREATE,
    Permission.CLIENT_UPDATE,
    Permission.CLIENT_DELETE,
    Permission.EQUIPMENT_VIEW,
    Permission.MAINTENANCE_VIEW,
    Permission.USER_VIEW,
    Permission.EXPORT_DATA,
    Permission.FILE_VIEW,
    Permission.FILE_UPLOAD,
  ],
  [Role.DEPO_SORUMLUSU]: [
    Permission.EQUIPMENT_VIEW,
    Permission.EQUIPMENT_CREATE,
    Permission.EQUIPMENT_UPDATE,
    Permission.EQUIPMENT_DELETE,
    Permission.MAINTENANCE_VIEW,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_DELETE,
    Permission.PROJECT_VIEW,
    Permission.CLIENT_VIEW,
    Permission.EXPORT_DATA,
    Permission.FILE_VIEW,
    Permission.FILE_UPLOAD,
    Permission.FILE_DELETE,
  ],
  [Role.TEKNISYEN]: [
    Permission.PROJECT_VIEW,
    Permission.TASK_VIEW,
    Permission.CLIENT_VIEW,
    Permission.EQUIPMENT_VIEW,
    Permission.MAINTENANCE_VIEW,
    Permission.USER_VIEW,
    Permission.FILE_VIEW,
  ],
};

export const hasPermission = (
  userRole: string,
  permission: Permission,
  userPermissions?: string[]
): boolean => {
  if (userPermissions?.includes(permission)) {
    return true;
  }

  const role = userRole as Role;
  return rolePermissions[role]?.includes(permission) ?? false;
};

export const hasRole = (userRole: string, ...roles: Role[]): boolean => {
  return roles.includes(userRole as Role);
};
