name: Build Android APK

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    name: Build Next.js & Capacitor APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Setup Java JDK (Android için)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK Platform 36
        run: sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('client/android/**/*.gradle*', 'client/android/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install --legacy-peer-deps

      - name: Build Next.js Application
        working-directory: ./client
        env:
          NEXT_PUBLIC_APP_URL: https://skpro.com.tr
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
        run: npm run build


      - name: Sync Capacitor Android
        working-directory: ./client
        run: npx cap sync android

      - name: Build APK File Using Gradle
        working-directory: ./client/android
        run: ./gradlew assembleDebug --no-daemon

      - name: Rename APK for Production
        working-directory: ./client/android/app/build/outputs/apk/debug
        run: mv app-debug.apk SK-Production.apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v7
        with:
          name: SK-Production-Android-APK
          path: client/android/app/build/outputs/apk/debug/SK-Production.apk
          retention-days: 30
